/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Fanfinity Backend
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query'

import { computed, toValue, unref } from 'vue'
import type { MaybeRefOrGetter } from 'vue'

import type {
  Account,
  AccountCreate,
  CreateAccount400,
  CreateAccount401,
  CreateAccount409,
  CreateAccount422,
  CreateSupportSession400,
  CreateSupportSession401,
  CreateSupportSession403,
  CreateSupportSession404,
  CreateSupportSession422,
  EndSupportSession401,
  EndSupportSession403,
  EndSupportSession404,
  EndSupportSession422,
  GetAccount401,
  GetAccount403,
  GetAccount404,
  GetAccount422,
  GetMe401,
  GetMe422,
  HealthzHealthzGet200,
  InviteMember400,
  InviteMember401,
  InviteMember403,
  InviteMember404,
  InviteMember409,
  InviteMember422,
  ListAccounts401,
  ListAccounts422,
  ListAccountsParams,
  ListMembers401,
  ListMembers403,
  ListMembers404,
  ListMembers422,
  ListMembersParams,
  ListSupportSessions401,
  ListSupportSessions403,
  ListSupportSessions422,
  ListSupportSessionsParams,
  Me,
  Member,
  MemberInvite,
  PageAccount,
  PageMember,
  PageSupportSession,
  ReadyzReadyzGet200,
  RemoveMember401,
  RemoveMember403,
  RemoveMember404,
  RemoveMember422,
  SupportSessionCreate,
  SupportSessionCreated,
  VersionVersionGet200
} from './model'

import { customFetch } from './mutator.js'
type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type getMeResponse200 = {
  data: Me
  status: 200
}

export type getMeResponse401 = {
  data: GetMe401
  status: 401
}

export type getMeResponse422 = {
  data: GetMe422
  status: 422
}

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers
}
export type getMeResponseError = (getMeResponse401 | getMeResponse422) & {
  headers: Headers
}

export type getMeResponse = getMeResponseSuccess | getMeResponseError

export const getGetMeUrl = () => {
  return `/v1/me`
}

/**
 * @summary Get Me
 */
export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetMeQueryKey = () => {
  return ['v1', 'me'] as const
}

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe422
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal
  }) => getMe({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  >
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = GetMe401 | GetMe422

/**
 * @summary Get Me
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = GetMe401 | GetMe422
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}

export type createAccountResponse201 = {
  data: Account
  status: 201
}

export type createAccountResponse400 = {
  data: CreateAccount400
  status: 400
}

export type createAccountResponse401 = {
  data: CreateAccount401
  status: 401
}

export type createAccountResponse409 = {
  data: CreateAccount409
  status: 409
}

export type createAccountResponse422 = {
  data: CreateAccount422
  status: 422
}

export type createAccountResponseSuccess = createAccountResponse201 & {
  headers: Headers
}
export type createAccountResponseError = (
  | createAccountResponse400
  | createAccountResponse401
  | createAccountResponse409
  | createAccountResponse422
) & {
  headers: Headers
}

export type createAccountResponse =
  | createAccountResponseSuccess
  | createAccountResponseError

export const getCreateAccountUrl = () => {
  return `/v1/accounts`
}

/**
 * @summary Create Account Route
 */
export const createAccount = async (
  accountCreate: AccountCreate,
  options?: RequestInit
): Promise<createAccountResponse> => {
  return customFetch<createAccountResponse>(getCreateAccountUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(accountCreate)
  })
}

export const getCreateAccountMutationOptions = <
  TError =
    | CreateAccount400
    | CreateAccount401
    | CreateAccount409
    | CreateAccount422,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAccount>>,
    TError,
    { data: AccountCreate },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAccount>>,
  TError,
  { data: AccountCreate },
  TContext
> => {
  const mutationKey = ['createAccount']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAccount>>,
    { data: AccountCreate }
  > = props => {
    const { data } = props ?? {}

    return createAccount(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAccount>>
>
export type CreateAccountMutationBody = AccountCreate
export type CreateAccountMutationError =
  | CreateAccount400
  | CreateAccount401
  | CreateAccount409
  | CreateAccount422

/**
 * @summary Create Account Route
 */
export const useCreateAccount = <
  TError =
    | CreateAccount400
    | CreateAccount401
    | CreateAccount409
    | CreateAccount422,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAccount>>,
      TError,
      { data: AccountCreate },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createAccount>>,
  TError,
  { data: AccountCreate },
  TContext
> => {
  return useMutation(getCreateAccountMutationOptions(options), queryClient)
}

export type listAccountsResponse200 = {
  data: PageAccount
  status: 200
}

export type listAccountsResponse401 = {
  data: ListAccounts401
  status: 401
}

export type listAccountsResponse422 = {
  data: ListAccounts422
  status: 422
}

export type listAccountsResponseSuccess = listAccountsResponse200 & {
  headers: Headers
}
export type listAccountsResponseError = (
  | listAccountsResponse401
  | listAccountsResponse422
) & {
  headers: Headers
}

export type listAccountsResponse =
  | listAccountsResponseSuccess
  | listAccountsResponseError

export const getListAccountsUrl = (params?: ListAccountsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/v1/accounts?${stringifiedParams}`
    : `/v1/accounts`
}

/**
 * @summary List Accounts Route
 */
export const listAccounts = async (
  params?: ListAccountsParams,
  options?: RequestInit
): Promise<listAccountsResponse> => {
  return customFetch<listAccountsResponse>(getListAccountsUrl(params), {
    ...options,
    method: 'GET'
  })
}

export const getListAccountsQueryKey = (
  params?: MaybeRefOrGetter<ListAccountsParams>
) => {
  return ['v1', 'accounts', ...(params ? [params] : [])] as const
}

export const getListAccountsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAccounts>>,
  TError = ListAccounts401 | ListAccounts422
>(
  params?: MaybeRefOrGetter<ListAccountsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAccounts>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getListAccountsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAccounts>>> = ({
    signal
  }) => listAccounts(toValue(params), { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAccounts>>,
    TError,
    TData
  >
}

export type ListAccountsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAccounts>>
>
export type ListAccountsQueryError = ListAccounts401 | ListAccounts422

/**
 * @summary List Accounts Route
 */

export function useListAccounts<
  TData = Awaited<ReturnType<typeof listAccounts>>,
  TError = ListAccounts401 | ListAccounts422
>(
  params?: MaybeRefOrGetter<ListAccountsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAccounts>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListAccountsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}

export type getAccountResponse200 = {
  data: Account
  status: 200
}

export type getAccountResponse401 = {
  data: GetAccount401
  status: 401
}

export type getAccountResponse403 = {
  data: GetAccount403
  status: 403
}

export type getAccountResponse404 = {
  data: GetAccount404
  status: 404
}

export type getAccountResponse422 = {
  data: GetAccount422
  status: 422
}

export type getAccountResponseSuccess = getAccountResponse200 & {
  headers: Headers
}
export type getAccountResponseError = (
  | getAccountResponse401
  | getAccountResponse403
  | getAccountResponse404
  | getAccountResponse422
) & {
  headers: Headers
}

export type getAccountResponse =
  | getAccountResponseSuccess
  | getAccountResponseError

export const getGetAccountUrl = (accountId: string) => {
  return `/v1/accounts/${accountId}`
}

/**
 * @summary Get Account Route
 */
export const getAccount = async (
  accountId: string,
  options?: RequestInit
): Promise<getAccountResponse> => {
  return customFetch<getAccountResponse>(getGetAccountUrl(accountId), {
    ...options,
    method: 'GET'
  })
}

export const getGetAccountQueryKey = (accountId: MaybeRefOrGetter<string>) => {
  return ['v1', 'accounts', accountId] as const
}

export const getGetAccountQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccount>>,
  TError = GetAccount401 | GetAccount403 | GetAccount404 | GetAccount422
>(
  accountId: MaybeRefOrGetter<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAccount>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetAccountQueryKey(accountId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccount>>> = ({
    signal
  }) => getAccount(toValue(accountId), { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(accountId) !== null && toValue(accountId) !== undefined
    ),
    ...queryOptions
  } as UseQueryOptions<Awaited<ReturnType<typeof getAccount>>, TError, TData>
}

export type GetAccountQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccount>>
>
export type GetAccountQueryError =
  | GetAccount401
  | GetAccount403
  | GetAccount404
  | GetAccount422

/**
 * @summary Get Account Route
 */

export function useGetAccount<
  TData = Awaited<ReturnType<typeof getAccount>>,
  TError = GetAccount401 | GetAccount403 | GetAccount404 | GetAccount422
>(
  accountId: MaybeRefOrGetter<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAccount>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAccountQueryOptions(accountId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}

export type listMembersResponse200 = {
  data: PageMember
  status: 200
}

export type listMembersResponse401 = {
  data: ListMembers401
  status: 401
}

export type listMembersResponse403 = {
  data: ListMembers403
  status: 403
}

export type listMembersResponse404 = {
  data: ListMembers404
  status: 404
}

export type listMembersResponse422 = {
  data: ListMembers422
  status: 422
}

export type listMembersResponseSuccess = listMembersResponse200 & {
  headers: Headers
}
export type listMembersResponseError = (
  | listMembersResponse401
  | listMembersResponse403
  | listMembersResponse404
  | listMembersResponse422
) & {
  headers: Headers
}

export type listMembersResponse =
  | listMembersResponseSuccess
  | listMembersResponseError

export const getListMembersUrl = (
  accountId: string,
  params?: ListMembersParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/v1/accounts/${accountId}/members?${stringifiedParams}`
    : `/v1/accounts/${accountId}/members`
}

/**
 * @summary List Members Route
 */
export const listMembers = async (
  accountId: string,
  params?: ListMembersParams,
  options?: RequestInit
): Promise<listMembersResponse> => {
  return customFetch<listMembersResponse>(
    getListMembersUrl(accountId, params),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getListMembersQueryKey = (
  accountId: MaybeRefOrGetter<string>,
  params?: MaybeRefOrGetter<ListMembersParams>
) => {
  return [
    'v1',
    'accounts',
    accountId,
    'members',
    ...(params ? [params] : [])
  ] as const
}

export const getListMembersQueryOptions = <
  TData = Awaited<ReturnType<typeof listMembers>>,
  TError = ListMembers401 | ListMembers403 | ListMembers404 | ListMembers422
>(
  accountId: MaybeRefOrGetter<string>,
  params?: MaybeRefOrGetter<ListMembersParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getListMembersQueryKey(accountId, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMembers>>> = ({
    signal
  }) =>
    listMembers(toValue(accountId), toValue(params), {
      signal,
      ...requestOptions
    })

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(accountId) !== null && toValue(accountId) !== undefined
    ),
    ...queryOptions
  } as UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
}

export type ListMembersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMembers>>
>
export type ListMembersQueryError =
  | ListMembers401
  | ListMembers403
  | ListMembers404
  | ListMembers422

/**
 * @summary List Members Route
 */

export function useListMembers<
  TData = Awaited<ReturnType<typeof listMembers>>,
  TError = ListMembers401 | ListMembers403 | ListMembers404 | ListMembers422
>(
  accountId: MaybeRefOrGetter<string>,
  params?: MaybeRefOrGetter<ListMembersParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListMembersQueryOptions(accountId, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}

export type inviteMemberResponse201 = {
  data: Member
  status: 201
}

export type inviteMemberResponse400 = {
  data: InviteMember400
  status: 400
}

export type inviteMemberResponse401 = {
  data: InviteMember401
  status: 401
}

export type inviteMemberResponse403 = {
  data: InviteMember403
  status: 403
}

export type inviteMemberResponse404 = {
  data: InviteMember404
  status: 404
}

export type inviteMemberResponse409 = {
  data: InviteMember409
  status: 409
}

export type inviteMemberResponse422 = {
  data: InviteMember422
  status: 422
}

export type inviteMemberResponseSuccess = inviteMemberResponse201 & {
  headers: Headers
}
export type inviteMemberResponseError = (
  | inviteMemberResponse400
  | inviteMemberResponse401
  | inviteMemberResponse403
  | inviteMemberResponse404
  | inviteMemberResponse409
  | inviteMemberResponse422
) & {
  headers: Headers
}

export type inviteMemberResponse =
  | inviteMemberResponseSuccess
  | inviteMemberResponseError

export const getInviteMemberUrl = (accountId: string) => {
  return `/v1/accounts/${accountId}/members`
}

/**
 * @summary Invite Member Route
 */
export const inviteMember = async (
  accountId: string,
  memberInvite: MemberInvite,
  options?: RequestInit
): Promise<inviteMemberResponse> => {
  return customFetch<inviteMemberResponse>(getInviteMemberUrl(accountId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(memberInvite)
  })
}

export const getInviteMemberMutationOptions = <
  TError =
    | InviteMember400
    | InviteMember401
    | InviteMember403
    | InviteMember404
    | InviteMember409
    | InviteMember422,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof inviteMember>>,
    TError,
    { accountId: string; data: MemberInvite },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof inviteMember>>,
  TError,
  { accountId: string; data: MemberInvite },
  TContext
> => {
  const mutationKey = ['inviteMember']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof inviteMember>>,
    { accountId: string; data: MemberInvite }
  > = props => {
    const { accountId, data } = props ?? {}

    return inviteMember(accountId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type InviteMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof inviteMember>>
>
export type InviteMemberMutationBody = MemberInvite
export type InviteMemberMutationError =
  | InviteMember400
  | InviteMember401
  | InviteMember403
  | InviteMember404
  | InviteMember409
  | InviteMember422

/**
 * @summary Invite Member Route
 */
export const useInviteMember = <
  TError =
    | InviteMember400
    | InviteMember401
    | InviteMember403
    | InviteMember404
    | InviteMember409
    | InviteMember422,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof inviteMember>>,
      TError,
      { accountId: string; data: MemberInvite },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof inviteMember>>,
  TError,
  { accountId: string; data: MemberInvite },
  TContext
> => {
  return useMutation(getInviteMemberMutationOptions(options), queryClient)
}

export type removeMemberResponse204 = {
  data: void
  status: 204
}

export type removeMemberResponse401 = {
  data: RemoveMember401
  status: 401
}

export type removeMemberResponse403 = {
  data: RemoveMember403
  status: 403
}

export type removeMemberResponse404 = {
  data: RemoveMember404
  status: 404
}

export type removeMemberResponse422 = {
  data: RemoveMember422
  status: 422
}

export type removeMemberResponseSuccess = removeMemberResponse204 & {
  headers: Headers
}
export type removeMemberResponseError = (
  | removeMemberResponse401
  | removeMemberResponse403
  | removeMemberResponse404
  | removeMemberResponse422
) & {
  headers: Headers
}

export type removeMemberResponse =
  | removeMemberResponseSuccess
  | removeMemberResponseError

export const getRemoveMemberUrl = (accountId: string, userId: string) => {
  return `/v1/accounts/${accountId}/members/${userId}`
}

/**
 * @summary Remove Member Route
 */
export const removeMember = async (
  accountId: string,
  userId: string,
  options?: RequestInit
): Promise<removeMemberResponse> => {
  return customFetch<removeMemberResponse>(
    getRemoveMemberUrl(accountId, userId),
    {
      ...options,
      method: 'DELETE'
    }
  )
}

export const getRemoveMemberMutationOptions = <
  TError =
    | RemoveMember401
    | RemoveMember403
    | RemoveMember404
    | RemoveMember422,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeMember>>,
    TError,
    { accountId: string; userId: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeMember>>,
  TError,
  { accountId: string; userId: string },
  TContext
> => {
  const mutationKey = ['removeMember']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeMember>>,
    { accountId: string; userId: string }
  > = props => {
    const { accountId, userId } = props ?? {}

    return removeMember(accountId, userId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RemoveMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeMember>>
>

export type RemoveMemberMutationError =
  | RemoveMember401
  | RemoveMember403
  | RemoveMember404
  | RemoveMember422

/**
 * @summary Remove Member Route
 */
export const useRemoveMember = <
  TError =
    | RemoveMember401
    | RemoveMember403
    | RemoveMember404
    | RemoveMember422,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeMember>>,
      TError,
      { accountId: string; userId: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof removeMember>>,
  TError,
  { accountId: string; userId: string },
  TContext
> => {
  return useMutation(getRemoveMemberMutationOptions(options), queryClient)
}

export type createSupportSessionResponse201 = {
  data: SupportSessionCreated
  status: 201
}

export type createSupportSessionResponse400 = {
  data: CreateSupportSession400
  status: 400
}

export type createSupportSessionResponse401 = {
  data: CreateSupportSession401
  status: 401
}

export type createSupportSessionResponse403 = {
  data: CreateSupportSession403
  status: 403
}

export type createSupportSessionResponse404 = {
  data: CreateSupportSession404
  status: 404
}

export type createSupportSessionResponse422 = {
  data: CreateSupportSession422
  status: 422
}

export type createSupportSessionResponseSuccess =
  createSupportSessionResponse201 & {
    headers: Headers
  }
export type createSupportSessionResponseError = (
  | createSupportSessionResponse400
  | createSupportSessionResponse401
  | createSupportSessionResponse403
  | createSupportSessionResponse404
  | createSupportSessionResponse422
) & {
  headers: Headers
}

export type createSupportSessionResponse =
  | createSupportSessionResponseSuccess
  | createSupportSessionResponseError

export const getCreateSupportSessionUrl = () => {
  return `/v1/support-sessions`
}

/**
 * @summary Create Support Session Route
 */
export const createSupportSession = async (
  supportSessionCreate: SupportSessionCreate,
  options?: RequestInit
): Promise<createSupportSessionResponse> => {
  return customFetch<createSupportSessionResponse>(
    getCreateSupportSessionUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(supportSessionCreate)
    }
  )
}

export const getCreateSupportSessionMutationOptions = <
  TError =
    | CreateSupportSession400
    | CreateSupportSession401
    | CreateSupportSession403
    | CreateSupportSession404
    | CreateSupportSession422,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSupportSession>>,
    TError,
    { data: SupportSessionCreate },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSupportSession>>,
  TError,
  { data: SupportSessionCreate },
  TContext
> => {
  const mutationKey = ['createSupportSession']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSupportSession>>,
    { data: SupportSessionCreate }
  > = props => {
    const { data } = props ?? {}

    return createSupportSession(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateSupportSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSupportSession>>
>
export type CreateSupportSessionMutationBody = SupportSessionCreate
export type CreateSupportSessionMutationError =
  | CreateSupportSession400
  | CreateSupportSession401
  | CreateSupportSession403
  | CreateSupportSession404
  | CreateSupportSession422

/**
 * @summary Create Support Session Route
 */
export const useCreateSupportSession = <
  TError =
    | CreateSupportSession400
    | CreateSupportSession401
    | CreateSupportSession403
    | CreateSupportSession404
    | CreateSupportSession422,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSupportSession>>,
      TError,
      { data: SupportSessionCreate },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createSupportSession>>,
  TError,
  { data: SupportSessionCreate },
  TContext
> => {
  return useMutation(
    getCreateSupportSessionMutationOptions(options),
    queryClient
  )
}

export type listSupportSessionsResponse200 = {
  data: PageSupportSession
  status: 200
}

export type listSupportSessionsResponse401 = {
  data: ListSupportSessions401
  status: 401
}

export type listSupportSessionsResponse403 = {
  data: ListSupportSessions403
  status: 403
}

export type listSupportSessionsResponse422 = {
  data: ListSupportSessions422
  status: 422
}

export type listSupportSessionsResponseSuccess =
  listSupportSessionsResponse200 & {
    headers: Headers
  }
export type listSupportSessionsResponseError = (
  | listSupportSessionsResponse401
  | listSupportSessionsResponse403
  | listSupportSessionsResponse422
) & {
  headers: Headers
}

export type listSupportSessionsResponse =
  | listSupportSessionsResponseSuccess
  | listSupportSessionsResponseError

export const getListSupportSessionsUrl = (
  params?: ListSupportSessionsParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/v1/support-sessions?${stringifiedParams}`
    : `/v1/support-sessions`
}

/**
 * @summary List Support Sessions Route
 */
export const listSupportSessions = async (
  params?: ListSupportSessionsParams,
  options?: RequestInit
): Promise<listSupportSessionsResponse> => {
  return customFetch<listSupportSessionsResponse>(
    getListSupportSessionsUrl(params),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getListSupportSessionsQueryKey = (
  params?: MaybeRefOrGetter<ListSupportSessionsParams>
) => {
  return ['v1', 'support-sessions', ...(params ? [params] : [])] as const
}

export const getListSupportSessionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listSupportSessions>>,
  TError =
    | ListSupportSessions401
    | ListSupportSessions403
    | ListSupportSessions422
>(
  params?: MaybeRefOrGetter<ListSupportSessionsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSupportSessions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getListSupportSessionsQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listSupportSessions>>
  > = ({ signal }) =>
    listSupportSessions(toValue(params), { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSupportSessions>>,
    TError,
    TData
  >
}

export type ListSupportSessionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSupportSessions>>
>
export type ListSupportSessionsQueryError =
  | ListSupportSessions401
  | ListSupportSessions403
  | ListSupportSessions422

/**
 * @summary List Support Sessions Route
 */

export function useListSupportSessions<
  TData = Awaited<ReturnType<typeof listSupportSessions>>,
  TError =
    | ListSupportSessions401
    | ListSupportSessions403
    | ListSupportSessions422
>(
  params?: MaybeRefOrGetter<ListSupportSessionsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSupportSessions>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListSupportSessionsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}

export type endSupportSessionResponse204 = {
  data: void
  status: 204
}

export type endSupportSessionResponse401 = {
  data: EndSupportSession401
  status: 401
}

export type endSupportSessionResponse403 = {
  data: EndSupportSession403
  status: 403
}

export type endSupportSessionResponse404 = {
  data: EndSupportSession404
  status: 404
}

export type endSupportSessionResponse422 = {
  data: EndSupportSession422
  status: 422
}

export type endSupportSessionResponseSuccess = endSupportSessionResponse204 & {
  headers: Headers
}
export type endSupportSessionResponseError = (
  | endSupportSessionResponse401
  | endSupportSessionResponse403
  | endSupportSessionResponse404
  | endSupportSessionResponse422
) & {
  headers: Headers
}

export type endSupportSessionResponse =
  | endSupportSessionResponseSuccess
  | endSupportSessionResponseError

export const getEndSupportSessionUrl = (sessionId: string) => {
  return `/v1/support-sessions/${sessionId}`
}

/**
 * @summary End Support Session Route
 */
export const endSupportSession = async (
  sessionId: string,
  options?: RequestInit
): Promise<endSupportSessionResponse> => {
  return customFetch<endSupportSessionResponse>(
    getEndSupportSessionUrl(sessionId),
    {
      ...options,
      method: 'DELETE'
    }
  )
}

export const getEndSupportSessionMutationOptions = <
  TError =
    | EndSupportSession401
    | EndSupportSession403
    | EndSupportSession404
    | EndSupportSession422,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof endSupportSession>>,
    TError,
    { sessionId: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof endSupportSession>>,
  TError,
  { sessionId: string },
  TContext
> => {
  const mutationKey = ['endSupportSession']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof endSupportSession>>,
    { sessionId: string }
  > = props => {
    const { sessionId } = props ?? {}

    return endSupportSession(sessionId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type EndSupportSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof endSupportSession>>
>

export type EndSupportSessionMutationError =
  | EndSupportSession401
  | EndSupportSession403
  | EndSupportSession404
  | EndSupportSession422

/**
 * @summary End Support Session Route
 */
export const useEndSupportSession = <
  TError =
    | EndSupportSession401
    | EndSupportSession403
    | EndSupportSession404
    | EndSupportSession422,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof endSupportSession>>,
      TError,
      { sessionId: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof endSupportSession>>,
  TError,
  { sessionId: string },
  TContext
> => {
  return useMutation(getEndSupportSessionMutationOptions(options), queryClient)
}

export type versionVersionGetResponse200 = {
  data: VersionVersionGet200
  status: 200
}

export type versionVersionGetResponseSuccess = versionVersionGetResponse200 & {
  headers: Headers
}

export type versionVersionGetResponse = versionVersionGetResponseSuccess

export const getVersionVersionGetUrl = () => {
  return `/version`
}

/**
 * @summary Build & release info
 */
export const versionVersionGet = async (
  options?: RequestInit
): Promise<versionVersionGetResponse> => {
  return customFetch<versionVersionGetResponse>(getVersionVersionGetUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getVersionVersionGetQueryKey = () => {
  return ['version'] as const
}

export const getVersionVersionGetQueryOptions = <
  TData = Awaited<ReturnType<typeof versionVersionGet>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof versionVersionGet>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getVersionVersionGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof versionVersionGet>>
  > = ({ signal }) => versionVersionGet({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof versionVersionGet>>,
    TError,
    TData
  >
}

export type VersionVersionGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof versionVersionGet>>
>
export type VersionVersionGetQueryError = unknown

/**
 * @summary Build & release info
 */

export function useVersionVersionGet<
  TData = Awaited<ReturnType<typeof versionVersionGet>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof versionVersionGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getVersionVersionGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}

export type healthzHealthzGetResponse200 = {
  data: HealthzHealthzGet200
  status: 200
}

export type healthzHealthzGetResponseSuccess = healthzHealthzGetResponse200 & {
  headers: Headers
}

export type healthzHealthzGetResponse = healthzHealthzGetResponseSuccess

export const getHealthzHealthzGetUrl = () => {
  return `/healthz`
}

/**
 * @summary Liveness probe
 */
export const healthzHealthzGet = async (
  options?: RequestInit
): Promise<healthzHealthzGetResponse> => {
  return customFetch<healthzHealthzGetResponse>(getHealthzHealthzGetUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getHealthzHealthzGetQueryKey = () => {
  return ['healthz'] as const
}

export const getHealthzHealthzGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof healthzHealthzGet>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getHealthzHealthzGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthzHealthzGet>>
  > = ({ signal }) => healthzHealthzGet({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthzHealthzGet>>,
    TError,
    TData
  >
}

export type HealthzHealthzGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthzHealthzGet>>
>
export type HealthzHealthzGetQueryError = unknown

/**
 * @summary Liveness probe
 */

export function useHealthzHealthzGet<
  TData = Awaited<ReturnType<typeof healthzHealthzGet>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthzHealthzGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getHealthzHealthzGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}

export type readyzReadyzGetResponse200 = {
  data: ReadyzReadyzGet200
  status: 200
}

export type readyzReadyzGetResponseSuccess = readyzReadyzGetResponse200 & {
  headers: Headers
}

export type readyzReadyzGetResponse = readyzReadyzGetResponseSuccess

export const getReadyzReadyzGetUrl = () => {
  return `/readyz`
}

/**
 * @summary Readiness probe
 */
export const readyzReadyzGet = async (
  options?: RequestInit
): Promise<readyzReadyzGetResponse> => {
  return customFetch<readyzReadyzGetResponse>(getReadyzReadyzGetUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getReadyzReadyzGetQueryKey = () => {
  return ['readyz'] as const
}

export const getReadyzReadyzGetQueryOptions = <
  TData = Awaited<ReturnType<typeof readyzReadyzGet>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof readyzReadyzGet>>, TError, TData>
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getReadyzReadyzGetQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof readyzReadyzGet>>> = ({
    signal
  }) => readyzReadyzGet({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof readyzReadyzGet>>,
    TError,
    TData
  >
}

export type ReadyzReadyzGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof readyzReadyzGet>>
>
export type ReadyzReadyzGetQueryError = unknown

/**
 * @summary Readiness probe
 */

export function useReadyzReadyzGet<
  TData = Awaited<ReturnType<typeof readyzReadyzGet>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof readyzReadyzGet>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getReadyzReadyzGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >

  return query
}
