/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface _ZidInstallReport {
  store_id: string;
  store_uuid?: string | null;
  domain?: string | null;
  frontend_store_id?: string | null;
}
