/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface Account {
  id: string
  name: string
  slug: string
  created_at: string
  jitsu_workspace_id?: string | null
}
