/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { DisplayName } from './displayName'

/**
 * Super-admin creation of a login user. Provisions a Firebase Auth user plus a personal workspace account they own — the same path as public self-registration, so the user can sign in to the dashboard with these credentials.
 */
export interface AdminAccountUserCreate {
  email: string
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string
  display_name?: DisplayName | null
}
