/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AccountMembership } from './accountMembership'
import type { User } from './user'

/**
 * The created login user and the memberships provisioned for them.
 */
export interface AdminAccountUserCreated {
  user: User
  memberships: AccountMembership[]
}
