/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { BigqueryDestinationConfig } from './bigqueryDestinationConfig'
import type { DestinationConfig } from './destinationConfig'
import type { GoogleAdsDestinationConfig } from './googleAdsDestinationConfig'
import type { MetaConversionsDestinationConfig } from './metaConversionsDestinationConfig'
import type { PostgresDestinationConfig } from './postgresDestinationConfig'
import type { S3DestinationConfig } from './s3DestinationConfig'
import type { SnowflakeDestinationConfig } from './snowflakeDestinationConfig'
import type { TiktokEventsDestinationConfig } from './tiktokEventsDestinationConfig'
import type { WebhookDestinationConfig } from './webhookDestinationConfig'

/**
 * The config for a destination, selected by its `destination_type`. Every credential field is write-only: sent on create or update, returned as `"***"`.
 *
 * `DestinationConfig` (the ClickHouse variant) is the shipped shape and is referenced rather than restated.
 */
export type AnyDestinationConfig =
  | DestinationConfig
  | PostgresDestinationConfig
  | BigqueryDestinationConfig
  | SnowflakeDestinationConfig
  | MetaConversionsDestinationConfig
  | TiktokEventsDestinationConfig
  | GoogleAdsDestinationConfig
  | WebhookDestinationConfig
  | S3DestinationConfig
