/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ApiTokenScope } from './apiTokenScope'

export interface ApiToken {
  id: string
  account_id: string
  name: string
  /** Last four characters. */
  hint: string
  scopes: ApiTokenScope[]
  /** User id of the member who minted it. */
  created_by: string
  created_at: string
  last_used_at?: string | null
  expires_at?: string | null
}
