/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ApiToken } from './apiToken'

export interface ApiTokenCreated {
  token: ApiToken
  /** The token. Shown once; not retrievable afterwards. */
  plaintext: string
}
