/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Coarse on purpose: a token holds fewer permissions than a role, not a different set.
 */
export type ApiTokenScope = (typeof ApiTokenScope)[keyof typeof ApiTokenScope]

export const ApiTokenScope = {
  read: 'read',
  write: 'write',
  admin: 'admin'
} as const
