/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ApiTokenScope } from './apiTokenScope'

export interface ApiTokenCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
  /** @minItems 1 */
  scopes: ApiTokenScope[]
  /** Omit for a token that does not expire. */
  expires_at?: string | null
}
