/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend API
 * Spec-first contract. Authentication is a Google Cloud Identity Platform (Firebase) ID token passed as `Authorization: Bearer <token>`; the backend verifies it and derives the user. Authorization is account-scoped RBAC (owner/admin/member/viewer). The business API is versioned under `/v1`; list endpoints are paginated (`page`/`size` → `{items, total, page, size, pages}`, the fastapi-pagination default `Page` format), and POSTs accept an optional `Idempotency-Key` header for safe retries. Health probes (/healthz, /readyz) and /version are defined directly in app/main.py and are intentionally outside this spec (and unversioned).
 *
 * OpenAPI spec version: 0.1.0
 */
import type { Problem } from './problem'

/**
 * Upstream service (Firebase Auth) returned an error
 */
export type BadGatewayResponse = Problem
