/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface BigqueryDestinationConfig {
  project_id: string
  dataset: string
  location?: string | null
  /** Service-account JSON key. Held by the backend; never returned. */
  service_account_key: string
}
