/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface BodyLogin {
  grant_type?: string
  username?: string
  password?: string
}
