/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Compression = (typeof Compression)[keyof typeof Compression]

export const Compression = {
  none: 'none',
  gzip: 'gzip'
} as const
