/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { DestinationType } from './destinationType'
import type { Kind } from './kind'
import type { Protocol } from './protocol'
import type { Status } from './status'

/**
 * A source or destination type the platform supports.
 */
export interface Connector {
  /** Stable slug, e.g. `zid`, `meta-conversions-api`. */
  id: string
  name: string
  kind: Kind
  description?: string | null
  /** For a source connector: `event_stream` or `cloud_app`. */
  source_type?: string | null
  destination_type?: DestinationType | null
  protocol?: Protocol | null
  /** Connector image, for an Airbyte-protocol connector. */
  package?: string | null
  version: string
  /** Icon key served by this API. Not a third-party URL — `img-src` is `'self'`. */
  icon?: string | null
  tags?: string[] | null
  status: Status
  /** Needs an authorization before it can sync. */
  requires_oauth?: boolean | null
}
