/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Registry pull credentials, if the image is private.
 */
export type ConnectorImageCreateCredentials = { [key: string]: unknown } | null
