/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectionTestResultDetails } from './connectionTestResultDetails'

/**
 * A failed test is a `200` with `ok: false`, not a `4xx`. The request succeeded — it is the connection that did not, and the dashboard needs the reason to render rather than an exception to catch.
 */
export interface ConnectionTestResult {
  ok: boolean
  /** Why it failed, safe to show a user. Null when `ok` is true. */
  error?: string | null
  latency_ms?: number | null
  checked_at: string
  /** Connector-specific diagnostics — permissions found, tables visible, API version reached. */
  details?: ConnectionTestResultDetails
}
