/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * JSON Schema. `format: password` on a property marks it as a secret the form should mask and store by reference.
 */
export type ConnectorSpecConfigSchema = { [key: string]: unknown } | null
