/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorSpecConfigSchema } from './connectorSpecConfigSchema'
import type { Mode } from './mode'

/**
 * The config schema a connector needs, as JSON Schema, so a create form can be rendered from it rather than hand-built per connector. `pending` means the backend is still fetching it from the connector image.
 */
export interface ConnectorSpec {
  connector_id: string
  version: string
  pending: boolean
  error?: string | null
  /** JSON Schema. `format: password` on a property marks it as a secret the form should mask and store by reference. */
  config_schema?: ConnectorSpecConfigSchema
  supported_modes?: Mode[] | null
  documentation_url?: string | null
}
