/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorImageCreateCredentials } from './connectorImageCreateCredentials'

export interface ConnectorImageCreate {
  package: string
  version: string
  /** Registry pull credentials, if the image is private. */
  credentials?: ConnectorImageCreateCredentials
}
