/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Connector-specific diagnostics — permissions found, tables visible, API version reached.
 */
export type ConnectionTestResultDetails = { [key: string]: unknown } | null
