/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Protocol1 } from './protocol1'
import type { Status1 } from './status1'

export interface ConnectorImage {
  id: string
  account_id: string
  /** Image reference, e.g. `ghcr.io/acme/source-internal`. */
  package: string
  version: string
  protocol?: Protocol1 | null
  status: Status1
  error?: string | null
  created_at: string
}
