/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * One per-minute bucket of the throughput series.
 */
export interface DashboardBucket {
  /** Start of the minute (UTC) */
  bucket: string
  received: number
  errors: number
  /** Null when the analytics store is unavailable */
  delivered?: number | null
}
