/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-source rollup for the dashboard flow panel.
 */
export interface DashboardSourceStat {
  id: string
  name: string
  slug: string
  source_type: string
  is_enabled: boolean
  /** Number of pipelines reading from this source */
  pipe_count: number
  /** Incoming events for this source in the window */
  events_received: number
}
