/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Headline counters for the dashboard stat cards.
 */
export interface DashboardTotals {
  sources: number
  sources_enabled: number
  destinations: number
  destinations_enabled: number
  pipes: number
  pipes_enabled: number
  /** Incoming events across all enabled sources in the window */
  events_received: number
  /** Error-level incoming-log records in the window */
  errors: number
  /** Rows written to the destinations' ClickHouse events tables in the window; null when the analytics store is unavailable */
  events_delivered?: number | null
}
