/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-pipeline rollup for the dashboard flow panel.
 */
export interface DashboardPipeStat {
  id: string
  name: string
  is_enabled: boolean
  source_id: string
  source_name?: string | null
  destination_id: string
  destination_name?: string | null
}
