/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardBucket } from './dashboardBucket'
import type { DashboardDestinationStat } from './dashboardDestinationStat'
import type { DashboardPipeStat } from './dashboardPipeStat'
import type { DashboardSourceStat } from './dashboardSourceStat'
import type { DashboardTotals } from './dashboardTotals'
import type { LiveEvent } from './liveEvent'

/**
 * The aggregated payload behind the dashboard home screen. All counts cover the requested window ending at ``updated_at``.
 */
export interface DashboardOverview {
  updated_at: string
  window_start: string
  window_end: string
  totals: DashboardTotals
  /** One entry per minute of the window, zero-filled, oldest first */
  buckets: DashboardBucket[]
  sources: DashboardSourceStat[]
  destinations: DashboardDestinationStat[]
  pipes: DashboardPipeStat[]
  /** Most recent incoming events, newest first (at most 10) */
  recent_events: LiveEvent[]
  /** Most recent error-level records, newest first (at most 10) */
  recent_errors: LiveEvent[]
}
