/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-destination rollup for the dashboard flow panel.
 */
export interface DashboardDestinationStat {
  id: string
  name: string
  slug: string
  destination_type: string
  is_enabled: boolean
  /** Number of pipelines delivering to this destination */
  pipe_count: number
  /** Rows written to this destination's ClickHouse events table in the window; null when unknown (no database yet, or store unavailable) */
  events_delivered?: number | null
}
