/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * RFC 9457 problem details, served as `application/problem+json`. Every error response in this contract uses this shape. The dashboard surfaces `detail` and throws `ApiError` carrying `status` plus this body.
 */
export type DeleteIngestDomain403 = {
  type?: string | null
  title: string
  status: number
  detail?: string | null
  instance?: string | null
}
