/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { DestinationColumn } from './destinationColumn'
import type { DestinationQueryResultRowsItem } from './destinationQueryResultRowsItem'

export interface DestinationQueryResult {
  columns: DestinationColumn[]
  rows: DestinationQueryResultRowsItem[]
  /** @minimum 0 */
  row_count: number
  /** True when the result was capped at the row limit. */
  truncated?: boolean | null
  /**
   * The offset this page starts at.
   * @minimum 0
   */
  offset: number
  /**
   * The limit this page was requested with.
   * @minimum 0
   */
  limit: number
  /**
   * Query execution time in milliseconds.
   * @minimum 0
   */
  elapsed_ms: number
}
