/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { DestinationColumn } from './destinationColumn'
import type { Rows } from './rows'

export interface DestinationTable {
  name: string
  engine?: string | null
  /** Approximate row count. */
  rows?: Rows | null
  /** The table's columns, so one endpoint feeds both the tables tab and the SQL console's table tree. */
  columns: DestinationColumn[]
}
