/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single read-only SELECT to run against the destination.
 */
export interface DestinationQueryRequest {
  /**
   * One read-only SELECT statement.
   * @minLength 1
   * @maxLength 10000
   */
  sql: string
  /** Rows to skip before returning the window. */
  offset?: number | null
  /** Maximum rows to return. The result is truncated when more match. */
  limit?: number | null
}
