/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AnyDestinationConfig } from './anyDestinationConfig'

export interface Destination {
  id: string
  account_id: string
  name: string
  slug: string
  destination_type: string
  jitsu_destination_id?: string | null
  is_enabled: boolean
  created_at: string
  updated_at: string
  /** The destination config, typed by `destination_type`. Credential fields are masked to `"***"` in responses. */
  config?: AnyDestinationConfig | null
  /** Auto-provisioned ClickHouse database name. Null while provisioning is pending. */
  clickhouse_database?: string | null
}
