/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Protocol } from './protocol'

export interface DestinationConfig {
  /** host:port pairs, e.g. ['my-ch.example.com:443'] */
  hosts: string[]
  protocol?: Protocol | null
  database?: string | null
  username?: string | null
  /** Always "***" in API responses */
  password?: string | null
}
