/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { DestinationColumn } from './destinationColumn'
import type { DestinationRowsPageRowsItem } from './destinationRowsPageRowsItem'

/**
 * A page of rows from one destination table.
 */
export interface DestinationRowsPage {
  columns: DestinationColumn[]
  rows: DestinationRowsPageRowsItem[]
  /** @minimum 0 */
  total: number
  /** @minimum 1 */
  page: number
  /** @minimum 1 */
  size: number
  /** @minimum 0 */
  pages: number
}
