/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AnyDestinationConfig } from './anyDestinationConfig'

/**
 * Unsaved changes to test against a saved destination. `config`, when given, is merged per-field with the stored config before the test runs; a secret field set to `"***"`, `"__MASKED_BY_JITSU__"`, `""`, or `null` keeps the stored value.
 */
export interface DestinationTestOverride {
  config?: AnyDestinationConfig | null
}
