/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Selects which `AnyDestinationConfig` variant applies. Extend this and the union together.
 */
export type DestinationType =
  (typeof DestinationType)[keyof typeof DestinationType]

export const DestinationType = {
  clickhouse: 'clickhouse',
  postgres: 'postgres',
  bigquery: 'bigquery',
  snowflake: 'snowflake',
  'meta-conversions-api': 'meta-conversions-api',
  'tiktok-events-api': 'tiktok-events-api',
  'google-ads': 'google-ads',
  webhook: 'webhook',
  s3: 's3'
} as const
