/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AnyDestinationConfig } from './anyDestinationConfig'
import type { DestinationType } from './destinationType'

/**
 * An unsaved destination to test. Secrets may be sent by reference (`secret://NAME`) instead of inline.
 */
export interface DestinationTestRequest {
  destination_type: DestinationType
  config: AnyDestinationConfig
}
