/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Extra connection parameters, e.g. `secure`, `verify`, `connection_timeout`.
 */
export type DestinationConfigParameters = { [key: string]: string } | null
