/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Fanfinity Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * RFC 9457 problem details.
 */
export type EndSupportSession422 = {
  type?: string | null
  title: string
  status: number
  detail?: string | null
  instance?: string | null
}
