/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { EventSummary } from './eventSummary';

/**
 * One page of event summaries.
 */
export interface EventSummaryPage {
  items: EventSummary[];
  /** @minimum 0 */
  total: number;
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  size: number;
  /** @minimum 0 */
  pages: number;
}
