/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Event = (typeof Event)[keyof typeof Event]

export const Event = {
  all: 'all',
  sync: 'sync',
  batch: 'batch',
  dead: 'dead',
  account: 'account'
} as const
