/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Format = (typeof Format)[keyof typeof Format]

export const Format = {
  ndjson: 'ndjson',
  parquet: 'parquet',
  csv: 'csv'
} as const
