/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Kind2 } from './kind2'

/**
 * A transform in the account library. `PipelineFunction` is an *instance* of one attached to a pipeline — this is the definition behind it.
 */
export interface FunctionDefinition {
  id: string
  account_id: string
  name: string
  slug: string
  description?: string | null
  kind: Kind2
  /** TypeScript, run in the backend sandbox. */
  code: string
  /** @minimum 1 */
  version: number
  /** Platform template this came from, if any. */
  template?: string | null
  template_version?: number | null
  /** Above `template_version` means an upgrade is available. */
  latest_template_version?: number | null
  attached_pipeline_ids?: string[] | null
  created_at: string
  updated_at: string
}
