/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * The event as it came out. Null means the function dropped it — which is success for a filter.
 */
export type FunctionTestResultResult = { [key: string]: unknown } | null
