/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface FunctionUpdate {
  name?: string | null
  description?: string | null
  code?: string | null
}
