/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { FunctionTestRequestEvent } from './functionTestRequestEvent'

export interface FunctionTestRequest {
  /** A sample event to run the function on. */
  event: FunctionTestRequestEvent
  /** Unsaved code to run instead of the stored version, so the editor can test before saving. */
  code?: string | null
}
