/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { FunctionTestResultResult } from './functionTestResultResult'
import type { SyncRunLogEntry } from './syncRunLogEntry'

/**
 * A function that throws is a `200` with `ok: false` — the run happened, and the editor needs the error to display.
 */
export interface FunctionTestResult {
  ok: boolean
  /** The event as it came out. Null means the function dropped it — which is success for a filter. */
  result?: FunctionTestResultResult
  dropped: boolean
  error?: string | null
  logs: SyncRunLogEntry[]
  duration_ms?: number | null
}
