/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Kind1 } from './kind1'

export interface FunctionCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
  /** @pattern ^[a-z0-9][a-z0-9-]*$ */
  slug: string
  description?: string | null
  kind?: Kind1 | null
  code?: string | null
  /** Instantiate from this template instead of sending `code`. */
  template?: string | null
}
