/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type GetDashboardOverviewParams = {
  /**
   * Window size in minutes; counts and buckets cover (now - minutes, now)
   * @minimum 5
   * @maximum 180
   */
  minutes?: number
}
