/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface GoogleAdsDestinationConfig {
  /** Ads customer id, digits only. */
  customer_id: string
  /** Manager account id, when access is via an MCC. */
  login_customer_id?: string | null
  conversion_action_id: string
  /** The grant to send under. Google Ads authorizes via OAuth, not a static token — see Authorizations. */
  oauth_authorization_id: string
}
