/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { QueueHealth } from './queueHealth'
import type { Status2 } from './status2'

/**
 * Whether this account's data is actually flowing. Not the same question as `/healthz`, which is about the service.
 */
export interface HealthReport {
  status: Status2
  generated_at: string
  queues: QueueHealth[]
}
