/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface IdentifierType {
  key: string
  name: string
  /** Safe to stitch on deterministically. A shared device id is not. */
  is_unique: boolean
  /** Masked on read unless the caller's role permits otherwise. */
  is_pii: boolean
  distinct_count?: number | null
  /** Share of events carrying it. A rare identifier is a poor thing to stitch on. */
  coverage?: number | null
}
