/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { IdentifierType } from './identifierType'

export interface IdentifierTypeList {
  items: IdentifierType[]
}
