/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CertificateStatus } from './certificateStatus'
import type { DnsRecord } from './dnsRecord'
import type { Status3 } from './status3'

export interface IngestDomain {
  id: string
  account_id: string
  /** Fully-qualified, e.g. `events.acme.com`. */
  domain: string
  status: Status3
  certificate_status: CertificateStatus
  /** What the customer has to create. Returned on create and while `pending`. */
  dns_records?: DnsRecord[] | null
  error?: string | null
  verified_at?: string | null
  created_at: string
}
