/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Kind = (typeof Kind)[keyof typeof Kind]

export const Kind = {
  source: 'source',
  destination: 'destination'
} as const
