/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Kind4 = (typeof Kind4)[keyof typeof Kind4]

export const Kind4 = {
  public: 'public',
  private: 'private'
} as const
