/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Kind3 = (typeof Kind3)[keyof typeof Kind3]

export const Kind3 = {
  source: 'source',
  destination: 'destination'
} as const
