/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Kind1 = (typeof Kind1)[keyof typeof Kind1]

export const Kind1 = {
  transform: 'transform',
  filter: 'filter',
  enrich: 'enrich'
} as const
