/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * What it does to an event: reshape it, drop it, or add to it.
 */
export type Kind2 = (typeof Kind2)[keyof typeof Kind2]

export const Kind2 = {
  transform: 'transform',
  filter: 'filter',
  enrich: 'enrich'
} as const
