/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type ListSourceSyncRunsParams = {
  /**
   * Page number
   * @minimum 1
   */
  page?: number
  /**
   * Page size
   * @minimum 1
   * @maximum 100
   */
  size?: number
}
