/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type ListLiveEventsParams = {
  /**
   * Maximum number of events to return
   * @minimum 1
   * @maximum 1000
   */
  limit?: number
  /**
   * Restrict to this source's Jitsu site/stream
   */
  source_id?: string | null
  /**
   * Only events at or after this time
   */
  start?: string | null
  /**
   * Only events at or before this time
   */
  end?: string | null
  /**
   * 'all' (default) or 'error'
   * @pattern ^(all|error)$
   */
  level?: string
  /**
   * Free-text search forwarded to the Jitsu log API
   */
  search?: string | null
}
