/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type ListSourceSyncRunLogsLevel =
  (typeof ListSourceSyncRunLogsLevel)[keyof typeof ListSourceSyncRunLogsLevel]

export const ListSourceSyncRunLogsLevel = {
  all: 'all',
  info: 'info',
  warn: 'warn',
  error: 'error'
} as const
