/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { LiveEvent } from './liveEvent'

/**
 * A list of live incoming events (newest first).
 */
export interface LiveEventList {
  items: LiveEvent[]
}
