/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { LiveEventContext } from './liveEventContext'
import type { LiveEventEvent } from './liveEventEvent'
import type { LiveEventIngestPayload } from './liveEventIngestPayload'

/**
 * One incoming event from the Jitsu incoming log, normalized to the shape the dashboard's live-events table renders.
 */
export interface LiveEvent {
  /** Synthetic id (log timestamp + row index) */
  id: string
  /** Raw log timestamp from Jitsu */
  date: string
  level: string
  /** The Jitsu site/stream id (log actor) this event came from */
  site_id: string
  /** The backend source that owns the site, when known */
  source_id?: string | null
  ingest_type?: string | null
  /** Event kind (track/page/identify) */
  type?: string | null
  message_id?: string | null
  status?: string | null
  error?: string | null
  write_key?: string | null
  origin_domain?: string | null
  host?: string | null
  page_url?: string | null
  page_path?: string | null
  page_title?: string | null
  user_id?: string | null
  email?: string | null
  anonymous_id?: string | null
  referring_domain?: string | null
  /** The analytics event payload (ingest httpPayload) */
  event?: LiveEventEvent
  /** The event context block */
  context?: LiveEventContext
  /** The full parsed ingest payload (raw event) */
  ingest_payload?: LiveEventIngestPayload
  /** The raw request body when it was a string */
  unparsed_payload?: string | null
  /** Destination names/tags the event was routed to */
  destinations: string[]
}
