/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * The full parsed ingest payload (raw event)
 */
export type LiveEventIngestPayload = { [key: string]: unknown } | null
