/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';

export interface MemberInvite {
  email: string;
  role: Role;
}
