/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface MetaConversionsDestinationConfig {
  /** Pixel or dataset id. */
  pixel_id: string
  /** System-user token with `ads_management`. */
  access_token: string
  /** Routes events to the Events Manager test tool instead of counting them. */
  test_event_code?: string | null
  log_request?: boolean | null
}
