/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Method = (typeof Method)[keyof typeof Method]

export const Method = {
  POST: 'POST',
  PUT: 'PUT'
} as const
