/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * full pulls everything; incremental syncs since the last watermark; date_range uses date_from/date_to.
 */
export type Mode = (typeof Mode)[keyof typeof Mode]

export const Mode = {
  full: 'full',
  incremental: 'incremental',
  date_range: 'date_range'
} as const
