/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Event } from './event'

export interface NotificationChannelUpdate {
  name?: string | null
  events?: Event[] | null
  slack_webhook_url?: string | null
  emails?: string[] | null
  recurring_alerts_period_hours?: number | null
  summarize_batch_notifications_by_table?: boolean | null
  is_enabled?: boolean | null
}
