/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Channel } from './channel'
import type { Event } from './event'

export interface NotificationChannelCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
  channel: Channel
  events?: Event[] | null
  /** Required when `channel` is `slack`. */
  slack_webhook_url?: string | null
  /** Required when `channel` is `email`. */
  emails?: string[] | null
  recurring_alerts_period_hours?: number | null
  summarize_batch_notifications_by_table?: boolean | null
}
