/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Channel } from './channel'
import type { Event } from './event'

export interface NotificationChannel {
  id: string
  account_id: string
  name: string
  channel: Channel
  /** `dead` covers events that failed every retry and were dropped. */
  events: Event[]
  /** Write-only in practice — returned masked. */
  slack_webhook_url?: string | null
  emails?: string[] | null
  /** How long to wait before re-alerting on a condition that is still failing. 0 alerts every time. */
  recurring_alerts_period_hours?: number | null
  summarize_batch_notifications_by_table?: boolean | null
  is_enabled: boolean
  created_at: string
  updated_at: string
}
