/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ConnectorImage } from './connectorImage'

/**
 * A page of custom connector images.
 */
export interface PageConnectorImage {
  items: ConnectorImage[]
  /** @minimum 0 */
  total: number
  /** @minimum 1 */
  page: number
  /** @minimum 1 */
  size: number
  /** @minimum 0 */
  pages: number
}
