/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { SyncRunLogEntry } from './syncRunLogEntry'

/**
 * A page of sync run log lines.
 */
export interface PageSyncRunLogEntry {
  items: SyncRunLogEntry[]
  /** @minimum 0 */
  total: number
  /** @minimum 1 */
  page: number
  /** @minimum 1 */
  size: number
  /** @minimum 0 */
  pages: number
}
