/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Position } from './position'

export interface PipelineFunctionAttach {
  function_id: string
  /** Zero-based insertion point. Omit to append. */
  position?: Position | null
}
