/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface PipelineCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
  source_id: string
  destination_id: string
}
