/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { PipelineFunction } from './pipelineFunction'

export interface PipelineFunctionList {
  items: PipelineFunction[]
}
