/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { PipelineDiagramEdge } from './pipelineDiagramEdge'
import type { PipelineDiagramNode } from './pipelineDiagramNode'

export interface PipelineDiagram {
  nodes: PipelineDiagramNode[]
  edges: PipelineDiagramEdge[]
  window_minutes: number
  generated_at: string
}
