/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Status5 } from './status5'

/**
 * One pipeline, drawn from its source node to its destination node.
 */
export interface PipelineDiagramEdge {
  /** The pipeline id. */
  id: string
  source_id: string
  destination_id: string
  name: string
  is_enabled: boolean
  status: Status5
  /** @minimum 0 */
  events_in_window: number
  /** @minimum 0 */
  errors_in_window: number
  function_count?: number | null
}
