/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface PipelineFunctionOrder {
  /** Every attached function id, in execution order. Omitting one is a `422`, not a detach. */
  function_ids: string[]
}
