/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface Pipeline {
  id: string
  account_id: string
  name: string
  source_id: string
  destination_id: string
  jitsu_link_id?: string | null
  is_enabled: boolean
  created_at: string
  updated_at: string
}
