/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Kind3 } from './kind3'
import type { Status5 } from './status5'

export interface PipelineDiagramNode {
  id: string
  kind: Kind3
  name: string
  /** `source_type` or `destination_type`, for picking the icon. */
  subtype?: string | null
  is_enabled: boolean
  status: Status5
  /** @minimum 0 */
  events_in_window: number
}
