/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface PostgresDestinationConfig {
  host: string
  port?: number | null
  database: string
  schema?: string | null
  username: string
  password: string
  ssl?: boolean | null
}
