/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ProfileCount } from './profileCount'

export interface ProfileBuilder {
  id: string
  account_id: string
  name: string
  slug: string
  is_enabled: boolean
  /** Where built profiles are written. Null keeps them queryable through this API only. */
  destination_id?: string | null
  /** Identifiers to stitch on, most trusted first. */
  identifier_types: string[]
  /** Optional TypeScript computing derived traits, run per profile. */
  code?: string | null
  /** When it runs. Null means on demand. */
  cron?: string | null
  last_run_at?: string | null
  profile_count?: ProfileCount | null
  created_at: string
  updated_at: string
}
