/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface ProfileBuilderCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
  /** @pattern ^[a-z0-9][a-z0-9-]*$ */
  slug: string
  destination_id?: string | null
  /** @minItems 1 */
  identifier_types: string[]
  code?: string | null
  cron?: string | null
}
