/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface ProfileBuilderUpdate {
  name?: string | null
  is_enabled?: boolean | null
  destination_id?: string | null
  identifier_types?: string[] | null
  code?: string | null
  cron?: string | null
}
