/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Protocol1 = (typeof Protocol1)[keyof typeof Protocol1]

export const Protocol1 = {
  airbyte: 'airbyte'
} as const
