/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Protocol = typeof Protocol[keyof typeof Protocol];


export const Protocol = {
  http: 'http',
  https: 'https',
  clickhouse: 'clickhouse',
  'clickhouse-secure': 'clickhouse-secure',
} as const;
