/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Status7 } from './status7'

export interface QueueHealth {
  name: string
  /**
   * Events waiting. A depth that only grows is the signal worth alerting on.
   * @minimum 0
   */
  depth: number
  /**
   * Age of the oldest waiting event.
   * @minimum 0
   */
  lag_seconds: number
  /** @minimum 0 */
  throughput_per_minute: number
  status: Status7
}
