/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface RefreshRequest {
  /** The refresh_token returned by /v1/auth/token or /v1/register. */
  refresh_token: string
}
