/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AccountMembership } from './accountMembership';
import type { User } from './user';

export interface RegisterResponse {
  token: string;
  user: User;
  memberships: AccountMembership[];
}
