/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface RegisterRequest {
  email: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
  display_name?: string | null;
}
