/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Fanfinity Backend
 * OpenAPI spec version: 0.1.0
 */

export type Role = (typeof Role)[keyof typeof Role]

export const Role = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
  viewer: 'viewer'
} as const
