/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Compression } from './compression'
import type { Format } from './format'

export interface S3DestinationConfig {
  bucket: string
  region: string
  /** Key prefix. Supports `{date}` and `{table}` placeholders. */
  prefix?: string | null
  access_key_id: string
  secret_access_key: string
  format?: Format | null
  compression?: Compression | null
}
