/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface SallaAuthorizeUrl {
  /**
   * Open this in the merchant's browser to complete the Salla OAuth handshake.
   * @minLength 1
   */
  authorize_url: string
}
