/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { SallaSourceConnectResultSnippet } from './sallaSourceConnectResultSnippet'
import type { SallaSourceConnectResultWebhooks } from './sallaSourceConnectResultWebhooks'

export interface SallaSourceConnectResult {
  status: string
  source_id: string
  store_id: string
  webhooks?: SallaSourceConnectResultWebhooks
  snippet?: SallaSourceConnectResultSnippet
}
