/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface SnowflakeDestinationConfig {
  /** Snowflake account identifier, e.g. `xy12345.eu-west-1`. */
  account: string
  warehouse: string
  database: string
  schema?: string | null
  role?: string | null
  username: string
  password: string
}
