/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Kind4 } from './kind4'
import type { Name } from './name'

/**
 * A client-generated write key supplied at source-create time. The browser mints both parts of the `keyId:secret` pair; the backend attaches them to the Jitsu stream verbatim.
 */
export interface SourceWriteKeyInput {
  /**
   * Caller-generated key id (the part before the colon in `keyId:secret`).
   * @minLength 8
   * @maxLength 64
   */
  id: string
  /**
   * Caller-generated secret (the part after the colon). Stored by Jitsu as-is.
   * @minLength 16
   * @maxLength 128
   */
  secret: string
  kind: Kind4
  /** Optional label, e.g. "marketing site". */
  name?: Name | null
  /** Omit for a key that does not expire. */
  expires_at?: string | null
}
