/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * An order record from the Zid Airbyte connector sync.
 */
export interface SourceOrder {
  id: number;
  status?: string | null;
  payment_status?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  [key: string]: unknown;
 }
