/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * A customer record from the Zid Airbyte connector sync.
 */
export interface SourceCustomer {
  id: number
  name?: string | null
  email?: string | null
  mobile?: string | null
  created_at?: string | null
  updated_at?: string | null
  [key: string]: unknown
}
