/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface SourceIngestSettingsUpdate {
  domains: string[]
  authorized_javascript_domains: string[]
  strict: boolean
  deduplicate_window_ms?: number | null
}
