/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * How an `event_stream` source accepts events. Jitsu keeps these on the stream object itself.
 */
export interface SourceIngestSettings {
  source_id: string
  /** Domains allowed to send events. Empty means any, which is only sensible for a server-side source. */
  domains: string[]
  /** Origins the browser SDK may run on. Enforced as CORS on the ingest endpoint. */
  authorized_javascript_domains: string[]
  /** Reject events that fail schema validation instead of passing them through and flagging them. */
  strict: boolean
  /** Drop a repeated `message_id` seen within this window. 0 disables deduplication. */
  deduplicate_window_ms?: number | null
  updated_at?: string | null
}
