/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface Source {
  id: string;
  account_id: string;
  name: string;
  slug: string;
  source_type: string;
  /** The Zid store id (only used when source_type is "zid"). */
  store_id?: string | null;
  /** The Zid storefront UUID (window.store_uuid), populated automatically on install. */
  store_uuid?: string | null;
  jitsu_site_id?: string | null;
  /** The Jitsu browser write key (same as jitsu_site_id). */
  write_key?: string | null;
  is_enabled: boolean;
  /** Upper bound (date_to) of the last successful sync; drives incremental sync. Null until the first successful sync. */
  last_synced_at?: string | null;
  created_at: string;
  updated_at: string;
}
