/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { SourceCatalogEntity } from './sourceCatalogEntity'

/**
 * What a cloud-app source can pull, and what is selected. `pending` means discovery is still running.
 */
export interface SourceCatalog {
  source_id: string
  pending: boolean
  discovered_at?: string | null
  /** Why the last discovery failed. */
  error?: string | null
  entities: SourceCatalogEntity[]
}
