/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface SourceCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
  /**
   * @minLength 1
   * @maxLength 255
   * @pattern ^[a-z0-9][a-z0-9-]*$
   */
  slug: string
  source_type?: string | null
  template_id?: string | null
  /** The Zid store id (required when source_type is "zid"). */
  store_id?: string | null
}
