/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface SourceCatalogUpdate {
  /** Entity keys to sync. A key discovery did not find is a `422`. */
  selected_entities: string[]
}
