/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Mode } from './mode'
import type { SourceCatalogEntitySchema } from './sourceCatalogEntitySchema'

/**
 * One thing a connector can pull — customers, orders, events.
 */
export interface SourceCatalogEntity {
  /** Stable identifier, e.g. `orders`. What `SyncTriggerRequest.entities` names. */
  key: string
  /** Human label. */
  name: string
  selected: boolean
  /** Not every entity supports incremental — one that cannot must be re-pulled in full. */
  supported_modes: Mode[]
  /** Field the incremental watermark tracks. */
  cursor_field?: string | null
  primary_key?: string[] | null
  /** JSON Schema of a record, as reported by the connector. */
  schema?: SourceCatalogEntitySchema
  record_count_estimate?: number | null
}
