/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { SourceCustomer } from './sourceCustomer';

/**
 * One page of per-source customers.
 */
export interface SourceCustomerPage {
  items: SourceCustomer[];
  /** @minimum 0 */
  total: number;
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  size: number;
  /** @minimum 0 */
  pages: number;
}
