/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Status7 = (typeof Status7)[keyof typeof Status7]

export const Status7 = {
  healthy: 'healthy',
  degraded: 'degraded',
  failing: 'failing'
} as const
