/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Status5 = (typeof Status5)[keyof typeof Status5]

export const Status5 = {
  healthy: 'healthy',
  degraded: 'degraded',
  failing: 'failing',
  idle: 'idle'
} as const
