/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Status3 = (typeof Status3)[keyof typeof Status3]

export const Status3 = {
  pending: 'pending',
  verified: 'verified',
  failed: 'failed'
} as const
