/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Status2 = (typeof Status2)[keyof typeof Status2]

export const Status2 = {
  healthy: 'healthy',
  degraded: 'degraded',
  failing: 'failing'
} as const
