/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Status1 = (typeof Status1)[keyof typeof Status1]

export const Status1 = {
  pending: 'pending',
  ready: 'ready',
  failed: 'failed'
} as const
