/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { SupportSession } from './supportSession';

export interface SupportSessionCreated {
  session: SupportSession;
  /** The short-lived support token — send as the X-Support-Token header. Valid until the session expires or is ended. */
  token: string;
}
