/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type SupportSessionStatus = typeof SupportSessionStatus[keyof typeof SupportSessionStatus];


export const SupportSessionStatus = {
  active: 'active',
  ended: 'ended',
  expired: 'expired',
} as const;
