/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { SupportSessionStatus } from './supportSessionStatus';

export interface SupportSession {
  id: string;
  account_id: string;
  staff_id: string;
  target_user_id?: string | null;
  reason: string;
  scopes: string[];
  status: SupportSessionStatus;
  expires_at: string;
  ended_at?: string | null;
  created_at: string;
}
