/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface SupportSessionCreate {
  account_id: string;
  /**
     * @minLength 1
     * @maxLength 500
     */
  reason: string;
  target_user_id?: string | null;
  /** Requested permissions; capped to the support-allowed set. */
  scopes?: string[] | null;
}
