/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Mode } from './mode';

/**
 * Request body to trigger a source sync.
 */
export interface SyncTriggerRequest {
  mode: Mode;
  /** Start of the window (required for date_range; ignored for full). */
  date_from?: string | null;
  /** End of the window (optional; defaults to now for date_range/incremental). */
  date_to?: string | null;
  /** Optional subset of entity keys to sync; defaults to all available. */
  entities?: string[] | null;
}
