/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Mode } from './mode'

export interface SyncScheduleUpdate {
  is_enabled: boolean
  cron?: string | null
  timezone?: string | null
  mode?: Mode | null
}
