/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Level } from './level'

export interface SyncRunLogEntry {
  timestamp: string
  level: Level
  message: string
  /** Which catalog entity the line concerns, when it concerns one. */
  entity?: string | null
}
