/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-entity record counts returned by the connector.
 */
export type SyncRunCounts = { [key: string]: unknown } | null
