/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Mode } from './mode'

export interface SyncSchedule {
  source_id: string
  is_enabled: boolean
  /** Five-field cron expression, interpreted in `timezone`. */
  cron?: string | null
  /** IANA name. Matters for a daily sync a customer expects at local midnight. */
  timezone?: string | null
  mode: Mode
  next_run_at?: string | null
  last_run_at?: string | null
}
