/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export interface TiktokEventsDestinationConfig {
  /** Pixel or offline event set id. */
  event_source_id: string
  access_token: string
  test_event_code?: string | null
}
