/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { TokenType } from './tokenType'

export interface TokenResponse {
  /** Firebase ID token for use as Bearer token */
  access_token: string
  token_type: TokenType
  /** Token lifetime in seconds */
  expires_in?: number | null
  /** Firebase refresh token. Exchange it at /v1/auth/refresh for a new access token when the current one expires. */
  refresh_token?: string | null
}
