/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type TokenType = typeof TokenType[keyof typeof TokenType];


export const TokenType = {
  bearer: 'bearer',
} as const;
