/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

export type Type = (typeof Type)[keyof typeof Type]

export const Type = {
  CNAME: 'CNAME',
  TXT: 'TXT',
  A: 'A'
} as const
