/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Sent with every request. Write-only, because these routinely carry an authorization header.
 */
export type WebhookDestinationConfigHeaders = { [key: string]: string } | null
