/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Method } from './method'
import type { WebhookDestinationConfigHeaders } from './webhookDestinationConfigHeaders'

export interface WebhookDestinationConfig {
  /** @minLength 1 */
  url: string
  method?: Method | null
  /** Sent with every request. Write-only, because these routinely carry an authorization header. */
  headers?: WebhookDestinationConfigHeaders
  batch_size?: number | null
  timeout_ms?: number | null
}
