/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { WriteKey } from './writeKey'

/**
 * A plain list rather than a page: a source has a handful of keys, not thousands.
 */
export interface WriteKeyList {
  items: WriteKey[]
}
