/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { WriteKey } from './writeKey'

/**
 * The one response that carries `plaintext`. It is not retrievable afterwards.
 */
export interface WriteKeyCreated {
  key: WriteKey
  /** The secret. Shown to the user once and never returned again. */
  plaintext: string
}
