/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Kind4 } from './kind4'

/**
 * A credential events are sent on. `public` keys are browser-safe; `private` keys are for server-side use only.
 */
export interface WriteKey {
  id: string
  source_id: string
  kind: Kind4
  /** Optional label, e.g. "marketing site". */
  name?: string | null
  /** Last four characters, for recognising a key without revealing it. */
  hint: string
  created_at: string
  /** Null if the key has never been used — which usually means an SDK was never wired up. */
  last_used_at?: string | null
  expires_at?: string | null
}
