/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { Kind4 } from './kind4'

export interface WriteKeyCreate {
  kind: Kind4
  name?: string | null
  /** Omit for a key that does not expire. */
  expires_at?: string | null
}
