/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * One Zid store this account has authorized (OAuth completed).
 */
export interface ZidConnection {
  /** The Zid dashboard store id; pass as `store_id` to createSource. */
  store_id: string
  /** Store display name captured from Zid; falls back to the domain, then the store id. */
  name: string
  /** Storefront domain, when known. */
  domain?: string | null
  /** Last time the store's tokens were updated (authorize or refresh). */
  connected_at: string
}
