/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Sfere Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ZidConnection } from './zidConnection'

/**
 * A plain list rather than a page: an account authorizes a handful of stores, not thousands.
 */
export interface ZidConnectionList {
  items: ZidConnection[]
}
