#!/usr/bin/env node
/**
 * brand-rename.mjs — Fanfinity → Sfere codemod.
 *
 * Rewrites the brand name across source, copy, mock data and docs. It is a
 * *selective* replace, not `s/fanfinity/sfere/g`: a blanket substitution would
 * repoint live infrastructure (the events proxy, the accounts API, the Identity
 * Platform tenant, the generated API client) at hosts and resources that do not
 * exist, and would silently invalidate a localStorage key that carries user
 * consent.
 *
 * Two lists carry the whole design:
 *
 *   SKIPPED_PATHS    — files the codemod never opens. Generated output, real
 *                      DNS records, secrets, and docs about the separately
 *                      named backend service.
 *   PRESERVED_SPANS  — exact substrings that survive even inside a file that is
 *                      otherwise rewritten. Each one is a live identifier.
 *
 * The implementation splits every file on a regex union of PRESERVED_SPANS,
 * replaces only in the segments between the matches, then rejoins. That way a
 * preserved span can sit on the same line as a renamed one and both are handled
 * correctly.
 *
 * Usage:
 *   node tools/brand-rename.mjs            # dry run — prints every change
 *   node tools/brand-rename.mjs --write    # apply
 *   node tools/brand-rename.mjs --verify   # list surviving occurrences + why
 *
 * Anything the codemod deliberately leaves behind is tracked in
 * todos/brand-rename-todo.md (gitignored — local working notes). `--verify`
 * output and that file must agree; a surviving hit with no TODO entry is a bug
 * in this script.
 *
 * Lives in tools/ rather than scripts/: scripts/ holds what the build and the
 * gates run, tools/ holds one-off maintenance like this.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

/* --------------------------------------------------------------------------
   1. Paths the codemod never opens.
   Each entry is a repo-relative prefix. A trailing slash means "the directory".
   -------------------------------------------------------------------------- */
const SKIPPED_PATHS = [
  // Never rewritten — no exceptions.
  { path: 'node_modules/', why: 'dependencies' },
  { path: '.git/', why: 'git internals' },
  { path: 'dist/', why: 'build output — regenerated by pnpm build' },
  { path: '.quasar/', why: 'generated by quasar prepare' },

  // Generated from the backend's OpenAPI spec. CLAUDE.md forbids hand-editing
  // these, and any local rename is reverted by the next `pnpm openapi`.
  { path: 'src/api/fanfinity.ts', why: 'orval output' },
  { path: 'src/api/model/', why: 'orval output' },
  { path: 'openapi/', why: 'upstream OpenAPI spec, pulled from the backend' },
  { path: 'orval.config.js', why: 'codegen config, keyed to the spec above' },

  // The accounts/RBAC service is a separate deployment still named Fanfinity.
  { path: 'docs/backend-auth-integration.md', why: 'documents that service' },

  // Real infrastructure and secrets.
  { path: 'public/CNAME', why: 'live DNS record for GitHub Pages' },
  { path: '.env', why: 'secrets — explicitly out of scope' },
  { path: '.env.example', why: 'mirrors .env; rename together with it' },

  // The codemod's own paperwork.
  { path: 'tools/brand-rename.mjs', why: 'this file' },
  {
    path: 'todos/',
    why: 'local working notes — gitignored, not shared history'
  }
]

/* --------------------------------------------------------------------------
   2. Substrings preserved inside files that are otherwise rewritten.
   Ordered longest-first so `api-staging.fanfinity.io` wins over
   `api.fanfinity.io`-style prefixes when the alternation is built.
   -------------------------------------------------------------------------- */
const PRESERVED_SPANS = [
  {
    span: 'api-staging.fanfinity.io',
    why: 'still an ingress alias for api-staging.sfere.io — CSP host'
  },
  {
    span: 'api.fanfinity.io',
    why: 'ingress alias for api.sfere.io — CSP host'
  },
  {
    span: 'fanfinity/merio',
    why: 'path of an existing capture harness in another repo'
  },
  {
    span: 'api/fanfinity',
    why: 'import path of the generated client (@/api/fanfinity, ./src/api/fanfinity.ts)'
  },
  {
    span: 'fanfinity-app',
    why: 'Identity Platform tenant name — a real GCP resource in project koratona-9791a'
  },
  {
    span: 'Fanfinity Backend',
    why: 'title of the separate backend service, as it appears in its OpenAPI spec'
  },
  {
    span: 'Fanfinity backend',
    why: 'prose form of the same separate service'
  }
]

/* File types worth opening at all. Everything else (images, fonts, lockfiles)
   is either binary or churn. */
const TEXT_EXTENSIONS = new Set([
  '.js',
  '.mjs',
  '.ts',
  '.vue',
  '.json',
  '.md',
  '.html',
  '.css',
  '.scss',
  '.yml',
  '.yaml',
  '.sh',
  '.txt'
])

/* --------------------------------------------------------------------------
   Replacement. Case is carried across so FANFINITY_SVC → SFERE_SVC and
   fanfinity.io → sfere.io both work from one pass.
   -------------------------------------------------------------------------- */
const BRAND = /Fanfinity|fanfinity|FANFINITY/g

const REPLACEMENTS = {
  Fanfinity: 'Sfere',
  fanfinity: 'sfere',
  FANFINITY: 'SFERE'
}

const escapeForRegex = value => value.replaceAll(/[.*+?^${}()|[\]\\]/g, '\\$&')

/* Longest-first so the alternation never matches a shorter preserved span
   inside a longer one. */
const preservedPattern = new RegExp(
  `(${PRESERVED_SPANS.map(entry => entry.span)
    .sort((a, b) => b.length - a.length)
    .map(escapeForRegex)
    .join('|')})`,
  'g'
)

/**
 * Replace the brand only in the parts of `source` that fall outside a preserved
 * span. String.split with a capturing group interleaves the two: even indices
 * are free text, odd indices are the preserved matches themselves.
 */
function rewriteBrand(source) {
  return source
    .split(preservedPattern)
    .map((segment, index) =>
      index % 2 === 1
        ? segment
        : segment.replaceAll(BRAND, m => REPLACEMENTS[m])
    )
    .join('')
}

const isSkipped = relativePath =>
  SKIPPED_PATHS.some(
    entry =>
      relativePath === entry.path ||
      (entry.path.endsWith('/') && relativePath.startsWith(entry.path))
  )

function* walk(directory) {
  for (const entry of readdirSync(directory)) {
    const absolute = join(directory, entry)
    const relativePath = relative(ROOT, absolute).split(sep).join('/')
    if (isSkipped(relativePath)) continue
    if (statSync(absolute).isDirectory()) {
      yield* walk(absolute)
      continue
    }
    const dot = entry.lastIndexOf('.')
    if (dot === -1 || !TEXT_EXTENSIONS.has(entry.slice(dot))) continue
    yield { absolute, relativePath }
  }
}

/* Which preserved span (if any) covers a given offset — used by --verify to
   explain every surviving occurrence. */
function explainSurvivor(source, offset) {
  for (const entry of PRESERVED_SPANS) {
    const start = source.lastIndexOf(entry.span, offset)
    if (start !== -1 && offset < start + entry.span.length) return entry.why
  }
  return null
}

/* -------------------------------------------------------------------------- */

const args = new Set(process.argv.slice(2))
const write = args.has('--write')
const verify = args.has('--verify')

if (verify) {
  const unexplained = []
  let explained = 0

  for (const { absolute, relativePath } of walk(ROOT)) {
    const source = readFileSync(absolute, 'utf8')
    for (const match of source.matchAll(BRAND)) {
      const why = explainSurvivor(source, match.index)
      if (why) {
        explained += 1
        continue
      }
      const line = source.slice(0, match.index).split('\n').length
      unexplained.push(`${relativePath}:${line}`)
    }
  }

  console.log('Skipped paths (never opened):')
  for (const entry of SKIPPED_PATHS)
    console.log(`  ${entry.path} — ${entry.why}`)
  console.log(`\nPreserved occurrences inside rewritten files: ${explained}`)
  for (const entry of PRESERVED_SPANS)
    console.log(`  ${entry.span} — ${entry.why}`)

  if (unexplained.length > 0) {
    console.log(`\nUNEXPLAINED (${unexplained.length}) — run without --verify:`)
    for (const hit of unexplained) console.log(`  ${hit}`)
    process.exitCode = 1
  } else {
    console.log('\nNo unexplained occurrences.')
  }
} else {
  let changedFiles = 0
  let changedOccurrences = 0

  for (const { absolute, relativePath } of walk(ROOT)) {
    const source = readFileSync(absolute, 'utf8')
    if (!BRAND.test(source)) continue
    BRAND.lastIndex = 0

    const next = rewriteBrand(source)
    if (next === source) continue

    const before = source.split('\n')
    const after = next.split('\n')
    const hits = before
      .map((line, index) => ({ index, line, updated: after[index] }))
      .filter(row => row.line !== row.updated)

    changedFiles += 1
    changedOccurrences += hits.length
    console.log(`\n${relativePath}`)
    for (const row of hits) {
      console.log(`  ${row.index + 1}- ${row.line.trim()}`)
      console.log(`  ${row.index + 1}+ ${row.updated.trim()}`)
    }

    if (write) writeFileSync(absolute, next)
  }

  const verb = write ? 'Rewrote' : 'Would rewrite'
  console.log(
    `\n${verb} ${changedOccurrences} lines across ${changedFiles} files.`
  )
  if (!write) console.log('Dry run — pass --write to apply.')
}
